# Generated by Django 3.1.7 on 2021-04-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(db_index=True, max_length=60)),
                ('Rank', models.IntegerField(default=1, null=True)),
                ('LadderScore', models.FloatField(db_index=True)),
                ('HealthyLifeExpectancy', models.FloatField()),
                ('Generosity', models.FloatField()),
                ('Gdp', models.FloatField()),
            ],
        ),
    ]
